compilers:
  - compiler:
      spec: gcc@11.3
      paths:
        cc: /share/modules/gcc/11.3.0/bin/gcc
        cxx: /share/modules/gcc/11.3.0/bin/g++
        f77: /share/modules/gcc/11.3.0/bin/gfortran
        fc: /share/modules/gcc/11.3.0/bin/gfortran
      flags: {}
      operating_system: rhel8
      target: any
      modules:
        - gcc/11.3.0
        - CUDA/12.5
        - openmpi/4.1.5-ucx1.13.1-cuda12.0
      extra_rpaths: []
      environment: {}
