packages:
  openmpi:
    externals:
      - spec: openmpi@5.0.3
        prefix: /share/contrib-modules/openmpi/ompi5.0.3-ucc1.3.x-ucx1.16.x-rocm6.2.0
        modules:
          - openmpi/5.0.3-ucc1.3.x-ucx1.16.x-rocm6.2.0
  rocprim:
    require: "@6.2.1"
    buildable: false
    externals:
      - spec: rocprim@6.2.1
        prefix: /opt/rocm-6.2.1
        modules:
          - rocm/6.2.1
  rocrand:
    require: "@6.2.1"
    buildable: false
    externals:
      - spec: rocrand@6.2.1
        prefix: /opt/rocm-6.2.1
        modules:
          - rocm/6.2.1
  rocthrust:
    require: "@6.2.1"
    buildable: false
    externals:
      - spec: rocthrust@6.2.1
        prefix: /opt/rocm-6.2.1
        modules:
          - rocm/6.2.1
  rocsparse:
    require: "@6.2.1"
    buildable: false
    externals:
      - spec: rocsparse@6.2.1
        prefix: /opt/rocm-6.2.1
        modules:
          - rocm/6.2.1
  hip:
    require: "@6.2.1"
    buildable: false
    externals:
      - spec: hip@6.2.1
        prefix: /opt/rocm-6.2.1
        modules:
          - rocm/6.2.1
  hsa-rocr-dev:
    require: "@6.2.1"
    buildable: false
    externals:
      - spec: hsa-rocr-dev@6.2.1
        prefix: /opt/rocm-6.2.1
        modules:
          - rocm/6.2.1
  llvm-amdgpu:
    require: "@6.2.1"
    buildable: false
    externals:
      - spec: llvm-amdgpu@6.2.1
        prefix: /opt/rocm-6.2.1/llvm
        modules:
          - rocm/6.2.1
  python:
    require: ~ssl
    externals:
    - spec: python@3.10.14
      prefix: /share/modules/python/3.10.14/
      modules:
      - python/3.10.14
  nalu-wind:
    require: "~trilinos-solvers"
  mpi:
    require: "openmpi"
  all:
    require:
      - "%clang@18.0"
    variants: amdgpu_target=gfx90a
