compilers:
  - compiler:
      spec: clang@18.0
      paths:
        cc: /opt/rocm-6.2.1/bin/amdclang
        cxx: /opt/rocm-6.2.1/bin/amdclang++
        f77: /opt/rocm-6.2.1/bin/amdflang
        fc: /opt/rocm-6.2.1/bin/amdflang
      flags: {}
      operating_system: rhel8
      target: any
      modules:
        - rocm/6.2.1
        - openmpi/5.0.3-ucc1.3.x-ucx1.16.x-rocm6.2.0
      extra_rpaths: []
      environment: {}
